### PR TITLE
Implement Randomized SVD based embeddings

### PR DESCRIPTION
**Pull request by ghost**
This PR implements randomized SVD as detailed in https://arxiv.org/abs/0909.4061 
included are utilities for sparse matrices, a new embedder, and an example python script.

rSVD is a useful building block for embedding methods such as ProNE https://github.com/THUDM/ProNE/blob/master/proNE.py which use it.

This particular implementation is specialized to sparse, symmetric, square matrices as seen in large undirected graphs. It should be able to handle very large matrices >100M rows/cols given sufficient amounts of RAM, and enough running time. Low ranks return in seconds even for large matrices.

NOTE: I did not integrate super neatly with cloverleaf, I kind of just glued my code to yours. It ain't pretty but the Python script works! The only really sus part is dumping the matrix into an `EmbeddingStore`. 

As an aside, it's kind of neat to think about the duality of graphs and matrices, and that you can approach graph problems from a purely algebraic point of view.

### CODE REVIEW

**Comment by Refefer** [comment]
Hey, thanks for the contribution!  I'll read over it tonight :)

**Comment by ghost** [comment]
Visualizing the various methods on [wheel_graph](https://networkx.org/documentation/stable/reference/generated/networkx.generators.classic.wheel_graph.html) this comes out:

where `pre/cheby` are methods from ProNE, and `rand` is `rSVD`. Which is cool, because `wheel` is one hub node with many spokes, which is visible after embedding to `d=3`.

image

**Comment by ghost** [comment]
bump

**Comment by Refefer** [comment]
I've been digging into this and have a few questions.

1. It's not clear how I should evaluate correctness; given the 2009 paper cited in the comments, I assumed low rank estimations would lead to reasonably good recommendation performance but found it to be effectively random on HitRate.  I've added the pinterest dataset (mainly since it's relatively small) in ./examples/dataset/pinterest with an evaluation script; just need to swap out the embeddings.  The paper is a commitment to read at 70+ pages so any intuition on tuning would be helfpul
2. Can we wire up the indicator to the function?  It's helpful to get a sense of how long it will run.
3. Somewhat unrelated, but it reminds be of FastRP (https://arxiv.org/abs/1908.11512) and InstantEmbeddings(https://arxiv.org/pdf/2010.06992.pdf); curious if you have any thoughts on the comparison of them with this method.

**Comment by ghost** [comment]
1. A much shorter paper than the Halko one (which I also did not read) is https://www.ijcai.org/proceedings/2019/0594.pdf  `ProNE: Fast and Scalable Network Representation Learning` (which I did read).  My TLDR is that this is a generic matrix decomposition technique, which can be applied to all kinds of large matrices, so even if it doesn't work on adjacency matrix, maybe it'll work on a different one. I will look into this. 

    I agree about evaluation performance, having run this on the Pinterest dataset I was only getting `5% @ HR-5`, and `10% @ HR-10`, so fairly bad. We can close this PR off for now, I will revisit when ready.

    RE: correctness, I compared my implementation to the one in https://github.com/THUDM/ProNE which has evaluations for various datasets, and a pristine python version here: https://github.com/gwgundersen/randomized-svd/blob/master/rsvd.py in pure Python.

    RE: tuning, it's related to the error estimate of the calculation, you can choose a larger random matrix with `n_samples` (defaults to 2*dim), and/or more iterations (usually just `n_subspace_iters=1` or 2) to get a better estimate. It converges the same value for each matrix, so no "fine-tuning".

2. Yes I will do this :+1: 

3. FastRP seems similar, the key difference is rather than reducing the adjacency matrix, they reduce a "node similarity" matrix, which could be a good idea to try. InstantEmbedding also seems to implicitly perform a matrix factorization, there is mention of it under section `A1 VERSE as Matrix Factorization`.

**Comment by Refefer** [comment]
Sounds good; I'll close for now.

**Pull request closed without merging**
